schema: "http://localhost:3000/graphql"
documents: "src/queries/**/*.{graphql,gql}"
extensions:
  codegen:
    generates:
      src/generated/types.ts:
        plugins:
          - "typescript"
          - "typescript-operations"
      src/generated/react.ts:
        preset: import-types
        presetConfig:
          typesPath: ./types
        plugins:
          - "typescript-react-apollo"
