export const ACCOUNT_BRIDGE_NAME = "ACCOUNT_BRIDGE";
export const ACCOUNT_BRIDGE_CHECK_ACCOUNT = "ACCOUNT_CHECK_ACCOUNT";
export const ACCOUNT_BRIDGE_CREATE_BY_CREDENTIALS =
  "ACCOUNT_CREATE_BY_CREDENTIALS";
export const ACCOUNT_BRIDGE_GET_BY_CREDENTIALS = "ACCOUNT_GET_BY_CREDENTIALS";
