name: Build Desktop
on:
  release:
    types: [released]

jobs:
  build-desktop:
    if: startsWith(github.event.release.tag_name, 'desktop')

    strategy:
      fail-fast: false
      matrix:
        # Do not build for macOS and Windows: Too much cost
        # platform: [ubuntu-20.04, macos-latest, windows-latest]
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}
    name: Build Desktop App for ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: npm ci

      - name: Build JavaScript
        run: npm run build:common

      - name: Build App
        run: npm run build:desktop

      - name: Copy Builds
        run: npm run build:copy -- -p linux macos windows

      - name: Upload files to a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ./desktop-app/builds/**/*
