name: Build Mobile
on:
  release:
    types: [released]

jobs:
  build-android:
    if: startsWith(github.event.release.tag_name, 'mobile')

    runs-on: ubuntu-20.04
    name: Build Mobile App for Android

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Fastlane dependencies
        run: (cd mobile-app/android/ && bundle install)

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build JavaScript
        run: npm run build:common

      - name: Build App
        run: npm run build:android

      - name: Copy Builds
        run: npm run build:copy -- -p android

      - name: Upload files to a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ./mobile-app/builds/**/*

  # Do not build for iOS: Too much cost
  # build-ios:
  #   if: startsWith('mobile', github.event.release.tag_name)

  #   runs-on: macos-latest
  #   name: Build Mobile App for iOS

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.1'
  #         bundler-cache: true

  #     - name: Install Fastlane dependencies
  #       run: (cd mobile-app/ios/App/ && bundle install)

  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: 'npm'
  #         cache-dependency-path: '**/package-lock.json'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build JavaScript
  #       run: npm run build:common

  #     - name: Build App
  #       run: npm run build:ios

  #     - name: Copy Builds
  #       run: npm run build:copy -- -p ios

  #     - name: Upload files to a GitHub release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ github.event.release.tag_name }}
  #         files: ./mobile-app/builds/**/*
